version: '2'
services:
    bubblebattstore-app:
        image: bubblebattstore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bubblebattstore-postgresql:5432/BubbleBattStore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bubblebattstore-postgresql:
        extends:
            file: postgresql.yml
            service: bubblebattstore-postgresql
